import { BarChart2, Home, Package, ShoppingBag } from "lucide-react";

interface ILink {
  href: string;
  label: string;
  icon: React.ReactNode;
}

export const LINKS: ILink[] = [
  { href: "/dashboard/home", label: "Inicio", icon: <Home /> },
  { href: "/dashboard/products", label: "Productos", icon: <Package /> },
  { href: "/dashboard/graphics", label: "Gráficos", icon: <BarChart2 /> },
  { href: "/dashboard/sells", label: "Ventas", icon: <ShoppingBag /> },
];

export type Product = {
  id: number;
  name: string;
  description: string;
  price: number;
  category: string;
  image: string;
};

export const PRODUCTS: Product[] = [
  // Tortas
  {
    id: 1,
    name: "Torta de chocolate",
    description: "Bizcocho húmedo con cobertura de cacao y chips crujientes.",
    price: 28.5,
    category: "Tortas",
    image: "/hero.png",
  },
  {
    id: 7,
    name: "Torta de vainilla",
    description: "Bizcocho clásico con crema chantilly y trozos de fruta.",
    price: 24.0,
    category: "Tortas",
    image: "/mascot.svg",
  },
  {
    id: 8,
    name: "Torta tres leches",
    description: "Esponjoso bizcocho empapado en una mezcla de tres leches.",
    price: 26.5,
    category: "Tortas",
    image: "/window.svg",
  },
  {
    id: 9,
    name: "Torta red velvet",
    description: "Bizcocho rojo con frosting de queso crema suave.",
    price: 30.0,
    category: "Tortas",
    image: "/file.svg",
  },
  {
    id: 10,
    name: "Torta de zanahoria",
    description: "Receta clásica con nueces y cobertura de queso crema.",
    price: 25.0,
    category: "Tortas",
    image: "/globe.svg",
  },
  {
    id: 11,
    name: "Torta selva negra",
    description: "Capas de chocolate, cerezas y crema batida.",
    price: 32.0,
    category: "Tortas",
    image: "/vercel.svg",
  },
  {
    id: 12,
    name: "Torta de fresas",
    description: "Crema fresca con fresas naturales sobre bizcocho ligero.",
    price: 27.0,
    category: "Tortas",
    image: "/hero.png",
  },
  {
    id: 13,
    name: "Torta de naranja",
    description: "Bizcocho cítrico con glaseado de naranja confitada.",
    price: 23.5,
    category: "Tortas",
    image: "/mascot.svg",
  },
  {
    id: 14,
    name: "Torta opera",
    description: "Capas finas de almendra, café y ganache de chocolate.",
    price: 34.0,
    category: "Tortas",
    image: "/window.svg",
  },
  {
    id: 15,
    name: "Torta de café",
    description: "Bizcocho con crema de café y nueces tostadas.",
    price: 26.0,
    category: "Tortas",
    image: "/file.svg",
  },
  {
    id: 16,
    name: "Torta de coco",
    description: "Bizcocho de coco con crema y ralladura tostada.",
    price: 25.5,
    category: "Tortas",
    image: "/globe.svg",
  },

  // Panadería
  {
    id: 2,
    name: "Croissant de mantequilla",
    description: "Hojaldre dorado con capas ligeras y aroma a vainilla.",
    price: 4.2,
    category: "Panadería",
    image: "/mascot.svg",
  },
  {
    id: 17,
    name: "Pan francés",
    description: "Corteza crocante y miga aireada, recién horneado.",
    price: 1.5,
    category: "Panadería",
    image: "/vercel.svg",
  },
  {
    id: 18,
    name: "Baguette artesanal",
    description: "Tradicional baguette con masa madre y costra dorada.",
    price: 3.8,
    category: "Panadería",
    image: "/hero.png",
  },
  {
    id: 19,
    name: "Pan de campo",
    description: "Pan rústico de larga fermentación y miga consistente.",
    price: 5.2,
    category: "Panadería",
    image: "/window.svg",
  },
  {
    id: 20,
    name: "Pan integral",
    description: "Mezcla de harinas integrales con semillas variadas.",
    price: 4.5,
    category: "Panadería",
    image: "/file.svg",
  },
  {
    id: 21,
    name: "Pan de canela",
    description: "Roll dulce con canela, azúcar morena y glaseado.",
    price: 4.0,
    category: "Panadería",
    image: "/globe.svg",
  },
  {
    id: 22,
    name: "Bollo dulce",
    description: "Pan suave y esponjoso, ideal para el desayuno.",
    price: 2.5,
    category: "Panadería",
    image: "/vercel.svg",
  },
  {
    id: 23,
    name: "Pan de yuca",
    description: "Bocados elásticos de queso fresco y almidón de yuca.",
    price: 3.2,
    category: "Panadería",
    image: "/hero.png",
  },
  {
    id: 24,
    name: "Empanada de queso",
    description: "Hojaldre crujiente con relleno de queso fundido.",
    price: 3.5,
    category: "Panadería",
    image: "/mascot.svg",
  },
  {
    id: 25,
    name: "Concha mexicana",
    description: "Pan dulce esponjoso con cobertura crujiente de azúcar.",
    price: 2.8,
    category: "Panadería",
    image: "/window.svg",
  },
  {
    id: 26,
    name: "Focaccia de hierbas",
    description: "Pan italiano con aceite de oliva, romero y sal marina.",
    price: 6.0,
    category: "Panadería",
    image: "/file.svg",
  },

  // Postres
  {
    id: 3,
    name: "Cheesecake frutos rojos",
    description: "Base crocante, crema suave y mermelada artesanal.",
    price: 22.0,
    category: "Postres",
    image: "/window.svg",
  },
  {
    id: 27,
    name: "Tiramisú",
    description: "Capas de bizcocho con café, mascarpone y cacao.",
    price: 8.5,
    category: "Postres",
    image: "/globe.svg",
  },
  {
    id: 28,
    name: "Mousse de chocolate",
    description: "Espuma sedosa de chocolate semiamargo y crema batida.",
    price: 6.0,
    category: "Postres",
    image: "/vercel.svg",
  },
  {
    id: 29,
    name: "Crème brûlée",
    description: "Crema de vainilla con costra de azúcar caramelizada.",
    price: 7.5,
    category: "Postres",
    image: "/hero.png",
  },
  {
    id: 30,
    name: "Panna cotta",
    description: "Postre italiano con coulis de frutos rojos.",
    price: 6.8,
    category: "Postres",
    image: "/mascot.svg",
  },
  {
    id: 31,
    name: "Flan de caramelo",
    description: "Clásico flan casero con caramelo dorado.",
    price: 5.5,
    category: "Postres",
    image: "/window.svg",
  },
  {
    id: 32,
    name: "Profiteroles",
    description: "Choux rellenos de crema con salsa de chocolate.",
    price: 7.2,
    category: "Postres",
    image: "/file.svg",
  },
  {
    id: 33,
    name: "Pavlova",
    description: "Merengue crujiente con crema y frutas frescas.",
    price: 9.0,
    category: "Postres",
    image: "/globe.svg",
  },
  {
    id: 34,
    name: "Arroz con leche",
    description: "Cremoso postre con canela y ralladura de limón.",
    price: 4.5,
    category: "Postres",
    image: "/vercel.svg",
  },
  {
    id: 35,
    name: "Natilla casera",
    description: "Crema suave aromatizada con vainilla y canela.",
    price: 4.2,
    category: "Postres",
    image: "/hero.png",
  },
  {
    id: 36,
    name: "Trifle de frutas",
    description: "Capas de bizcocho, crema y frutas de temporada.",
    price: 8.0,
    category: "Postres",
    image: "/mascot.svg",
  },

  // Bocados
  {
    id: 4,
    name: "Brownie intenso",
    description: "Chocolate 70% cacao con nueces tostadas y sal marina.",
    price: 6.5,
    category: "Bocados",
    image: "/file.svg",
  },
  {
    id: 37,
    name: "Mini muffin",
    description: "Pequeño muffin esponjoso con chips de chocolate.",
    price: 2.0,
    category: "Bocados",
    image: "/window.svg",
  },
  {
    id: 38,
    name: "Trufa de chocolate",
    description: "Bocado fundente de chocolate negro y cacao.",
    price: 1.8,
    category: "Bocados",
    image: "/globe.svg",
  },
  {
    id: 39,
    name: "Macaron de pistacho",
    description: "Tapas de almendra rellenas con ganache de pistacho.",
    price: 2.5,
    category: "Bocados",
    image: "/vercel.svg",
  },
  {
    id: 40,
    name: "Cake pop",
    description: "Bocado de bizcocho cubierto con chocolate y decoración.",
    price: 2.2,
    category: "Bocados",
    image: "/hero.png",
  },
  {
    id: 41,
    name: "Donut glaseado",
    description: "Esponjosa rosquilla con glaseado clásico.",
    price: 2.8,
    category: "Bocados",
    image: "/mascot.svg",
  },
  {
    id: 42,
    name: "Mini éclair",
    description: "Choux relleno de crema y cobertura de chocolate.",
    price: 3.0,
    category: "Bocados",
    image: "/window.svg",
  },
  {
    id: 43,
    name: "Bombón relleno",
    description: "Chocolate fino con relleno de praliné de avellanas.",
    price: 1.6,
    category: "Bocados",
    image: "/file.svg",
  },
  {
    id: 44,
    name: "Bocado de coco",
    description: "Mordisco dulce de coco rallado y leche condensada.",
    price: 1.5,
    category: "Bocados",
    image: "/globe.svg",
  },
  {
    id: 45,
    name: "Petit four",
    description: "Pequeño dulce decorado, perfecto para acompañar el té.",
    price: 2.6,
    category: "Bocados",
    image: "/vercel.svg",
  },
  {
    id: 46,
    name: "Praliné de avellanas",
    description: "Mezcla crujiente de avellanas caramelizadas.",
    price: 2.4,
    category: "Bocados",
    image: "/hero.png",
  },

  // Tartas
  {
    id: 5,
    name: "Tarta de limón",
    description: "Crema cítrica balanceada con merengue suave y tostado.",
    price: 18.9,
    category: "Tartas",
    image: "/globe.svg",
  },
  {
    id: 47,
    name: "Tarta de manzana",
    description: "Manzanas en lámina sobre masa quebrada y canela.",
    price: 17.5,
    category: "Tartas",
    image: "/mascot.svg",
  },
  {
    id: 48,
    name: "Tarta de durazno",
    description: "Duraznos frescos con crema pastelera y brillo de jalea.",
    price: 18.0,
    category: "Tartas",
    image: "/window.svg",
  },
  {
    id: 49,
    name: "Tarta de chocolate",
    description: "Base de cacao con ganache intenso y avellanas.",
    price: 21.0,
    category: "Tartas",
    image: "/file.svg",
  },
  {
    id: 50,
    name: "Tarta de queso",
    description: "Estilo horneado con base de galleta y queso crema.",
    price: 20.0,
    category: "Tartas",
    image: "/vercel.svg",
  },
  {
    id: 51,
    name: "Tarta de almendras",
    description: "Crema frangipane con láminas de almendra tostada.",
    price: 19.5,
    category: "Tartas",
    image: "/hero.png",
  },
  {
    id: 52,
    name: "Tarta de pera",
    description: "Peras cocidas en almíbar sobre crema de almendra.",
    price: 19.0,
    category: "Tartas",
    image: "/mascot.svg",
  },
  {
    id: 53,
    name: "Tarta tatín",
    description: "Manzanas caramelizadas invertidas sobre masa hojaldrada.",
    price: 20.5,
    category: "Tartas",
    image: "/window.svg",
  },
  {
    id: 54,
    name: "Tarta de frutos rojos",
    description: "Crema pastelera con mix de frutos rojos frescos.",
    price: 22.5,
    category: "Tartas",
    image: "/globe.svg",
  },
  {
    id: 55,
    name: "Tarta de fresa",
    description: "Fresas naturales sobre crema y masa sablée.",
    price: 21.5,
    category: "Tartas",
    image: "/file.svg",
  },
  {
    id: 56,
    name: "Tarta de coco",
    description: "Crema de coco sobre base crujiente con coco tostado.",
    price: 18.5,
    category: "Tartas",
    image: "/vercel.svg",
  },

  // Galletas
  {
    id: 6,
    name: "Galletas vainilla",
    description: "Clásicas, mantecosas y perfectas para acompañar café.",
    price: 3.8,
    category: "Galletas",
    image: "/vercel.svg",
  },
  {
    id: 57,
    name: "Galletas chocochip",
    description:
      "Crujientes por fuera, suaves por dentro con chips de chocolate.",
    price: 4.0,
    category: "Galletas",
    image: "/hero.png",
  },
  {
    id: 58,
    name: "Galletas de avena",
    description: "Avena tostada con pasas y un toque de canela.",
    price: 3.5,
    category: "Galletas",
    image: "/mascot.svg",
  },
  {
    id: 59,
    name: "Galletas de jengibre",
    description: "Especiadas con jengibre, canela y melaza.",
    price: 3.8,
    category: "Galletas",
    image: "/window.svg",
  },
  {
    id: 60,
    name: "Galletas de coco",
    description: "Tiernas galletas con coco rallado y vainilla.",
    price: 3.6,
    category: "Galletas",
    image: "/file.svg",
  },
  {
    id: 61,
    name: "Galletas de almendra",
    description: "Crujientes con almendras laminadas y aroma cítrico.",
    price: 4.2,
    category: "Galletas",
    image: "/globe.svg",
  },
  {
    id: 62,
    name: "Macarons surtidos",
    description: "Set de macarons en sabores variados de temporada.",
    price: 5.5,
    category: "Galletas",
    image: "/vercel.svg",
  },
  {
    id: 63,
    name: "Galletas de mantequilla",
    description: "Receta tradicional con mantequilla francesa.",
    price: 3.4,
    category: "Galletas",
    image: "/hero.png",
  },
  {
    id: 64,
    name: "Galletas de canela",
    description: "Suaves con un intenso aroma a canela molida.",
    price: 3.5,
    category: "Galletas",
    image: "/mascot.svg",
  },
  {
    id: 65,
    name: "Alfajores",
    description: "Dos galletas de maicena unidas con dulce de leche.",
    price: 4.5,
    category: "Galletas",
    image: "/window.svg",
  },
  {
    id: 66,
    name: "Galletas con chispas",
    description: "Mantecosas con chispas de colores, ideales para niños.",
    price: 3.7,
    category: "Galletas",
    image: "/file.svg",
  },
];

export const PRODUCT_CATEGORIES = [
  "Tortas",
  "Panadería",
  "Postres",
  "Bocados",
  "Tartas",
  "Galletas",
];
